// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Mupxr4rUmaDE5TLm_Nrz8W1Ri36M8Fk',
    appId: '1:239729405706:android:a0b6d1013ac2b059ca94f3',
    messagingSenderId: '239729405706',
    projectId: 'bl-eb-app',
    storageBucket: 'bl-eb-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegzOZ3IkDlhgW9MZ6TZfdazBn7Kl8oB4',
    appId: '1:239729405706:ios:772a64300de0cdedca94f3',
    messagingSenderId: '239729405706',
    projectId: 'bl-eb-app',
    storageBucket: 'bl-eb-app.appspot.com',
    iosClientId: '239729405706-eboqnhvc3b3qg3bhn7go4fnctg4eu03h.apps.googleusercontent.com',
    iosBundleId: 'com.naas.i_employment',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegzOZ3IkDlhgW9MZ6TZfdazBn7Kl8oB4',
    appId: '1:239729405706:ios:772a64300de0cdedca94f3',
    messagingSenderId: '239729405706',
    projectId: 'bl-eb-app',
  );
}
